DROP TABLE IF EXISTS user_favs CASCADE;

CREATE TABLE user_favs (
  id SERIAL PRIMARY KEY NOT NULL,
  car_id INTEGER REFERENCES cars(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);